# Generated by Django 3.1.2 on 2021-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrdertb',
            fields=[
                ('CoId', models.AutoField(primary_key=True, serialize=False)),
                ('CoinPair', models.CharField(max_length=8, verbose_name='交易货币对')),
                ('UserUniqkey', models.CharField(max_length=12, verbose_name='用户唯一编号')),
                ('Bidorderid', models.CharField(max_length=12, verbose_name='买单的orderid')),
                ('Bidprice', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='买单的价格')),
                ('Bidqulity', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='买单的数量')),
                ('BidAmount', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='买单的成交金额')),
                ('BidCreateTime', models.CharField(max_length=20, verbose_name='买单创建时间')),
                ('Askorderid', models.CharField(max_length=12, verbose_name='卖单的orderid')),
                ('Askprice', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='卖单的价格')),
                ('Askqulity', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='卖单的数量')),
                ('AskAmount', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='卖单的成交金额')),
                ('AskCreateTime', models.CharField(max_length=20, verbose_name='卖单创建时间')),
                ('OrderProfit', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='本单收益')),
                ('OrderProfitrate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='本单收益率')),
            ],
        ),
        migrations.CreateModel(
            name='Task_info',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False)),
                ('Uniqueid', models.CharField(max_length=12, verbose_name='用户随机编号')),
                ('TaskName', models.CharField(max_length=12, verbose_name='任务名称')),
                ('TradePlantName', models.CharField(max_length=10, verbose_name='交易所名称')),
                ('CoinExchange', models.CharField(max_length=8, verbose_name='交易对名称')),
                ('HighestPrice', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='最高价格')),
                ('lowestPrice', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='最低价格')),
                ('lockNum', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='准备使用的Usdt个数')),
                ('gridnum', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='网格数量')),
                ('trate', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='每单利润')),
                ('task_flag', models.CharField(max_length=1, verbose_name='有效标记，0-失效，1-有效')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedate', models.CharField(blank=None, max_length=15, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRuninfo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Uniqueid', models.CharField(max_length=12, verbose_name='用户随机编号')),
                ('TaskName', models.CharField(max_length=12, verbose_name='任务名称')),
                ('taskstarttime', models.DateTimeField(auto_now_add=True, verbose_name='启动时间')),
                ('flag', models.CharField(max_length=1, verbose_name='运行标记，0-停止，1-运行中')),
                ('taskstoptime', models.CharField(blank=None, max_length=15, verbose_name='停止时间')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('Uniqueid', models.CharField(max_length=12, verbose_name='随机生成的用户随机编号')),
                ('ak', models.CharField(max_length=12, verbose_name='用户的appkey')),
                ('sk', models.CharField(max_length=18, verbose_name='用户的screatkey')),
                ('tradeplant', models.CharField(max_length=5, verbose_name='交易所')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
