# Generated by Django 3.1.2 on 2021-04-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePlant',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('plantName', models.CharField(max_length=10, verbose_name='交易所名称')),
                ('plantApiHost', models.CharField(max_length=20, verbose_name='交易所Api地址')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
