# Generated by Django 3.1.2 on 2021-04-28 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_tradeplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskruninfo',
            name='taskid',
            field=models.CharField(default=django.utils.timezone.now, max_length=4, verbose_name='任务的id'),
            preserve_default=False,
        ),
    ]
