# Generated by Django 3.1.2 on 2021-05-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_taskruninfo_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskruninfo',
            name='taskstarttime',
            field=models.CharField(blank=None, max_length=15, verbose_name='启动时间'),
        ),
    ]
