# Generated by Django 3.1.2 on 2021-05-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20210503_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_info',
            name='HighestPrice',
            field=models.CharField(max_length=8, verbose_name='最高价格'),
        ),
        migrations.AlterField(
            model_name='task_info',
            name='gridnum',
            field=models.CharField(max_length=8, verbose_name='网格数量'),
        ),
        migrations.AlterField(
            model_name='task_info',
            name='lockNum',
            field=models.CharField(max_length=8, verbose_name='准备使用的Usdt个数'),
        ),
        migrations.AlterField(
            model_name='task_info',
            name='lowestPrice',
            field=models.CharField(max_length=8, verbose_name='最低价格'),
        ),
        migrations.AlterField(
            model_name='task_info',
            name='trate',
            field=models.CharField(max_length=8, verbose_name='每单利润'),
        ),
    ]
